import { useEffect, useState } from 'react';
import { Alert, Button, Col, Container, Form, Row, Spinner } from 'react-bootstrap';
import * as adminService from '../../services/adminService';

function SettingsPage() {
  const [form, setForm] = useState(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { adminService.getSettings().then((response) => setForm(response.data)).catch((requestError) => setError(requestError.response?.data?.message || 'Não foi possível carregar as configurações.')); }, []);
  const save = async (event) => { event.preventDefault(); try { setForm((await adminService.updateSettings(form)).data); setMessage('Configurações guardadas com sucesso.'); setError(''); } catch (requestError) { setError(requestError.response?.data?.message || 'Não foi possível guardar as configurações.'); } };
  if (!form) return <div className="text-center py-5"><Spinner variant="warning" /></div>;
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <Container fluid className="py-4"><div className="rc-page-header"><div><span className="rc-eyebrow">Administração</span><h1>Configurações globais</h1><p>Defina os dados e regras comuns a toda a operação.</p></div></div>{message ? <Alert variant="success" dismissible onClose={() => setMessage('')}>{message}</Alert> : null}{error ? <Alert variant="danger">{error}</Alert> : null}<Form className="rc-card" onSubmit={save}><Row className="g-4"><Col md={6}><Form.Group><Form.Label>Nome da empresa</Form.Label><Form.Control required value={form.companyName} onChange={(event) => set('companyName', event.target.value)} /></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Moeda</Form.Label><Form.Select value={form.currency} onChange={(event) => set('currency', event.target.value)}><option value="EUR">Euro (EUR)</option><option value="USD">Dólar (USD)</option><option value="GBP">Libra (GBP)</option></Form.Select></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Email de apoio</Form.Label><Form.Control required type="email" value={form.supportEmail} onChange={(event) => set('supportEmail', event.target.value)} /></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Telefone de apoio</Form.Label><Form.Control required value={form.supportPhone} onChange={(event) => set('supportPhone', event.target.value)} /></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Antecedência para cancelamento</Form.Label><Form.Control type="number" min={0} value={form.cancellationHours} onChange={(event) => set('cancellationHours', Number(event.target.value))} /><Form.Text>Horas mínimas antes do levantamento.</Form.Text></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Aviso de levantamento</Form.Label><Form.Control type="number" min={0} value={form.upcomingReminderDays} onChange={(event) => set('upcomingReminderDays', Number(event.target.value))} /><Form.Text>Dias de antecedência da notificação.</Form.Text></Form.Group></Col><Col xs={12} className="text-end"><Button variant="warning" type="submit">Guardar configurações</Button></Col></Row></Form></Container>;
}
export default SettingsPage;
