const express = require('express');
const { authenticate, authorize } = require('../middleware/authMiddleware');
const controller = require('../controllers/customerFeatureController');
const router = express.Router();
router.post('/support/public', controller.createPublicTicket);
router.get('/reviews/public', controller.listPublicReviews);
router.use(authenticate);
router.get('/support', controller.listTickets);
router.post('/support', authorize(['cliente']), controller.createTicket);
router.get('/support/:id/messages', controller.listTicketMessages);
router.post('/support/:id/messages', controller.createTicketMessage);
router.patch('/support/:id', authorize(['admin', 'gestor']), controller.updateTicket);
router.delete('/support/:id', authorize(['admin']), controller.deleteTicket);
router.get('/reviews', authorize(['cliente']), controller.listReviews);
router.post('/reviews', authorize(['cliente']), controller.createReview);
router.get('/reviews/manage', authorize(['admin', 'gestor']), controller.listManagedReviews);
router.patch('/reviews/:id/moderate', authorize(['admin', 'gestor']), controller.moderateReview);
router.delete('/reviews/:id', authorize(['admin']), controller.deleteReview);
module.exports = router;
